name: Deploy to EC2

on:
push:
branches:
- main   # change if your branch is different

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd /home/ubuntu/task-manager-webapp
        git pull origin main
        docker pull rishabsingh12/taskflow-backend:latest
        docker pull rishabsingh12/taskflow-frontend:latest
        docker-compose down
        docker-compose up -d
        docker image prune -f
        echo "✅ Done!"

